info: "OpenAIRE Matomo Tracker"

Matomo_Parameters:
  #Matomo tracker Endpoint
  matomo_url: "http://localhost:5000"
  #matomo_url: "https://analytics.openaire.eu/"

  #Repository Base Url
  repository_base_url: "https://www.pedocs.de"
  #Matomo Repository Site ID
  idSite: 228
  #Matomo authenticastion token
  token_auth: "32846584f571be9b57488bf4088f30ea"
  #matomo parameters (default values)
  delay_after_failure: 10
  default_max_attempts: 3
  default_socket_timeout: 300
  #IP Anonymization
  ip_anonymization: false
  #Skip the n first lines to start parsing/importing data at a given line for the specified log file
  skip_lines: 0

  # Number of recorders. It should be set to the number of CPU cores in your server.
  # You can also experiment with higher values which may increase performance until a certain point
  recorders: 4
  recorder_min_hits: 1000
  #OAI-PMH Configuration
  oaipmh_preamble: "oai:www.pedocs.de-opus:"
  #oaipmh regular expressions to build the oaipmh id
  oaipmh_regex_metadata: "([0-9]*)"
  oaipmh_regex_download: "[0-9]*/([0-9)]*)"
  #Metadata Location (regexp supported)
  tracking_metadata:
  - "/frontdoor.php[^ ]*source_opus="
  #Item Location (regexp supported)
  tracking_download:
  - "/volltexte/"